(3, 4) Naumovec
sberbankjavaschool/homework pull request #110
Opened 2019-05-10 15:04 UTC by tatanka27

2019-05-10 17:33 UTC, kolmogorov-aa requested changes
Учитывая сложность задания, обещанную награду за ошибку и т.д. и т.п. 
исправьте замечания и задания выполнены.

..я просто устал уже ревьюить.

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new EmptyQuoteException("No quotes for specified amount!");
по-хорошему нужно документировать исключения в javadoc.
За это не снижаю оценку

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +                    new Date().toString(), operation.toString(), false);
Вы видели как форматирует дату метод toString()?

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +            return ClientOperation.SELL;
Ах, был бы такой метод, который конвертировал строку в енам...

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +        return Optional.empty();
Делать то будете? как мне это засчитывать?

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +        return Optional.of(beneficiary == Beneficiary.CLIENT ^ operation == ClientOperation.BUY
Сами додумались?

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +                ? prices.get(prices.size() - 1) : prices.get(0));
лучше тогда определять индекс в условии.
так чище будет

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +            Volume volumeTo = Volume.from(quotes.get(i).getVolumeSize().multiply(price));
выше про тернарник писал. тут аналогично.
не многовато ли quotes.get(i)?
Если этот лист - н-связный список, то какова сложность вашего алгоритма?
Понятно, что тут другой случай. Но лучше приучить себя сразу делать универсально И правильно.

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +    public List<ReverseQuote> getReverseQuotes(List<Quote> quotes, ClientOperation operation) {
Паблик?

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +            Volume volumeTo = Volume.from(quotes.get(i).getVolumeSize().multiply(price));
Метод то паблик, и quotes действительно может быть связным списком.
и вот мы получили сложность O( ___) на ровном месте!

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Solution.java
> +                } else {
Хорошо, лучше чем у других, даже на косяки указывать не хочется.

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +            throw new NullPointerException("Parameter beneficiary is null!");
https://tproger.ru/translations/10-ways-to-handle-null-in-java/

2019-05-10 17:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Solution.java
> +        FxResponse response = client.fetchResult(request);
У вас сервис и контроллер бросают кучу исключений. Нет желания пользователю в случае ошибки выдать что-нибудь вменяемое вместо стектрейса? =)

2019-05-10 19:32 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Solution.java
> +        FxResponse response = client.fetchResult(request);
Хочется! Буду решать.

2019-05-10 19:35 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +        return Optional.empty();
С delta не разобралась. Т.к. срок до 26, я бы еще подумала.

2019-05-10 19:40 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +        return Optional.of(beneficiary == Beneficiary.CLIENT ^ operation == ClientOperation.BUY
Если вы про xor, то я табличку нарисовала.
![xor](https://user-images.githubusercontent.com/49755327/57552437-8a960980-7374-11e9-92f5-0797d311bad8.jpg)

2019-05-10 19:41 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +        return Optional.of(beneficiary == Beneficiary.CLIENT ^ operation == ClientOperation.BUY
Если вы про xor, то я табличку рисовала.
![xor](https://user-images.githubusercontent.com/49755327/57552497-bf09c580-7374-11e9-9229-b1baeafa5b8b.jpg)

2019-05-10 19:57 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +            Volume volumeTo = Volume.from(quotes.get(i).getVolumeSize().multiply(price));
Сделаю iterator

2019-05-10 19:57 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +    public List<ReverseQuote> getReverseQuotes(List<Quote> quotes, ClientOperation operation) {
Исправила

2019-05-10 19:59 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Solution.java
> +                } else {
А что за косяки?

2019-05-10 20:10 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new EmptyQuoteException("No quotes for specified amount!");
Учту на будущее. Пока добавила для примера в Calculator.

2019-05-10 20:12 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +                    new Date().toString(), operation.toString(), false);
Исправлю.

2019-05-10 20:21 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +            return ClientOperation.SELL;
Есть такой.

2019-05-10 20:28 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Solution.java
> +        FxResponse response = client.fetchResult(request);
Исправила.

2019-05-10 20:30 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +            throw new NullPointerException("Parameter beneficiary is null!");
Обязательно это учту и в следующий раз применю.

2019-05-10 20:45 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +                ? prices.get(prices.size() - 1) : prices.get(0));
Надеюсь, я правильно поняла и сделала.

2019-05-10 20:49 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +        return Optional.empty();
Примите тогда пока 4 задание

2019-05-10 21:08 UTC, tatanka27 commented
Не успела до 23.59.

2019-05-11 06:43 UTC, kolmogorov-aa approved these changes

2019-05-11 06:43 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +            q = iterator.next();
неплохо

2019-05-11 06:43 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Solution.java
> +        } catch (FxConversionException ex) {
я бы пошире поставил. типа до  runtime

2019-05-11 06:43 UTC, merged

2019-05-11 07:15 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCalculator.java
> +            q = iterator.next();
:)

2019-05-11 07:17 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Solution.java
> +        } catch (FxConversionException ex) {
Исправляю!