(5) Таргон
sberbankjavaschool/homework pull request #156
Opened 2019-05-14 21:51 UTC by NickTargon

2019-05-14 21:57 UTC, NickTargon commented
![image](https://user-images.githubusercontent.com/13822823/57735188-71f75d80-76ac-11e9-874e-695815c44f8d.png)

2019-05-15 06:11 UTC, kolmogorov-aa commented
Максимальная сумма миллион, а средняя - миллион и 10к? Это как так?

2019-05-15 06:13 UTC, kolmogorov-aa commented
Судя по картинке данные по суммам совпадают с объемом частично

2019-05-15 07:42 UTC, NickTargon commented
Понял где проблема, прийду домой - исправлю

2019-05-15 07:57 UTC, kolmogorov-aa approved these changes
Есть время переделать

2019-05-15 07:57 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +        }
Один хороший метод разбирали у строк

2019-05-15 07:57 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +        }
А это прям антипаттерн. Конкатенация в цикле. Ай ай

2019-05-15 07:57 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +            }
Не то чтобы я одобряю такой подход, просто сейчас его оценивать не буду.

2019-05-15 07:57 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +        Map map = [:].withDefault { key -> return [] } as LinkedHashMap<String, MergedResponses>
что тут происходит?

2019-05-15 07:57 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +}
типичная ошибка, типичное замечание:
Видно, что Вы используете типичный Java-подход. Но смысл задачи был показать, что для отдельных задач есть более удобные и подходящие решения. Зачем использовать конкатенации и условные конструкции, когда можно объявить одну многострочную переменную через """?
как-то так:
""" tra-ta-ta
${sellPreResult ?: 'Запросов по продажам не было'}
${buyPreResult ?: 'Запросов по покупкам не было'} """
Есть и более "вкусные" приемы, но вообще этого более ем достаточно.

Ещё я вижу вот какую проблему - смешение логик. Как мы говорили на одной из первых лекций - метод должен выполнять только одну функцию и делать это хорошо. (Класс тоже не должен быть сильно многозадачным).
Если бы было разделение на два этапа, то код был бы лаконичнее, чище, его было бы сложнее запороть другим разработчикам. Например, так:
- подготовка информации (данные можно хранить в мапе или, что предпочтительнее - специальном объекте (т.н. модель), откуда было бы удобно доставать значения на этапе рендера)

- рендер (можно представить в виде класа, который собирает шаблон по кускам, можно в виде шаблона из одной строки).

2019-05-15 07:57 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/MergedResponses.groovy
> +        this.prices = [response.getPrice()] as ArrayList<String>
было бы лучше вместо def'ов объявить их как List
Видя объявление этого класса совершенно не понятно что этот класс перед нами, как им можно пользоваться, какого типа данные.

2019-05-15 07:57 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/BodyData.groovy
> +    private def count
А так геттеры генерируются?

Дефы тоже не к месту.

2019-05-15 07:57 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +            String operation
Если выбирать между def через запятую и def вот так вот, я бы выбрал первое.
Но вообще это как-то неуместно такое количество локальных переменных.

2019-05-15 17:22 UTC, NickTargon commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +        }
заменил на .join()

2019-05-16 17:20 UTC, NickTargon commented
![image](https://user-images.githubusercontent.com/13822823/57873822-e00c6380-7817-11e9-9bf9-30b23cb58991.png)
Новая картинка, форматен тоже отличается, но очень далек от идеала, но на мой взгляд лучше чем первоначальный

2019-05-17 07:54 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/DataFromResponse.groovy
> +    String mostPopularCount = getPopular()[1]
ёлки-палки.
```
String mostPopular = getPopular()[0]
String mostPopularCount = getPopular()[1]
```
Ну что это такое? Это настолько неправильно, что аж хочется пальчиком погрозить.
Во-первых, getPopular() вызывается два раза. ЗАЧЕМ?
Во-вторых, какая-та мета-связь по индексу - что это вообще?
В-третьих, зачем это делать в объявлении полей, это лучше было бы в инициализаторе/конструкторе.
Судя по предыдущему коду Вы можете гораздо лучше. Спишу это на электромагнитные бури. ;)

2019-05-17 07:55 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/DataFromResponse.groovy
> +        responses.each { FxResponse response ->
всего два цикла по responses, лучше чем у остальных, но все равно излишне.
Думаю, с опытом придет и понимание.

2019-05-17 07:57 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/MergedResponses.groovy
> +        this.prices = [response.getPrice()] as ArrayList<BigDecimal>
как-то не очень лаконично получилось,

2019-05-17 07:58 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/MergedResponses.groovy
> +        List<BigDecimal> list = createAmountList()
что-то я поторопился createAmountList() - 4 раза вызывается.
А потом 4 раза по ним итерируетесь.
Возможно, что в самый первый раз Ваш код был эффективнее раз в 10.

2019-05-17 07:58 UTC, kolmogorov-aa commented on solutions/build.gradle
> +import org.gradle.api.artifacts.*
убрать. мержить не буду пока не уберете

2019-05-17 20:06 UTC, kolmogorov-aa requested changes
Удалить изменения общего файла

2019-05-18 08:04 UTC, kolmogorov-aa approved these changes

2019-05-18 08:04 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +        list.join('\n')
Для таких вещей есть стрингбилдер

2019-05-18 08:04 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/DataFromResponse.groovy
> +        Map map = [:] as LinkedHashMap<String, MergedResponses>
А почему выбрали LinkedHashMap?

2019-05-18 08:04 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/MergedResponses.groovy
> +        }
что-то мне подсказывает, что этот иф можно сократить ровно в 2 раза. в смысле убрать его вообще.
Особенно на груви.

2019-05-18 08:04 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/MergedResponses.groovy
> +    }
Такие условные конструкции свидетельствуют о слабой объектной ориентированности. 
Ну в принципе для начала сойдет.

2019-05-18 08:04 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/MergedResponses.groovy
> +    BigDecimal worstPriceBuyAmount
не то чтобы замечание, но наверное, все эти поля можно было бы в мапу засунуть.
Ну это так, альтернативный подход. (где-то значит нужно задокументировать состав мапы)

2019-05-18 08:04 UTC, kolmogorov-aa commented
START-TEST

2019-05-18 08:16 UTC, NickTargon commented on common/src/main/groovy/ru/sberbank/school/task03/util/DataFromResponse.groovy
> +        Map map = [:] as LinkedHashMap<String, MergedResponses>
для сохранения порядка добавления

2019-05-18 08:22 UTC, NickTargon commented on common/src/main/groovy/ru/sberbank/school/task03/util/MergedResponses.groovy
> +        }
например все строки типа this.bestPriceSellAmount = null

2019-05-18 15:20 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/DataFromResponse.groovy
> +        Map map = [:] as LinkedHashMap<String, MergedResponses>
не было вроде такого требования

2019-05-18 15:22 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/util/MergedResponses.groovy
> +        }
вообще нет, но ладно.

2019-05-18 15:22 UTC, merged