(5) Fedorov
sberbankjavaschool/homework pull request #166
Opened 2019-05-16 15:52 UTC by Ganzalo

2019-05-17 08:09 UTC, kolmogorov-aa commented
Сквош?

2019-05-17 08:18 UTC, kolmogorov-aa approved these changes
Неплохо, неплохо. Только мелкие замечания

2019-05-17 08:18 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +        println (result)
вот это лишнее

2019-05-17 08:18 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +        def gString = """Отчет об изменении котировок для валют ${map.keySet().join(", ")}\n\n"""
зачем использовать многострочную запись для однострочной строки?

2019-05-17 08:18 UTC, kolmogorov-aa commented on common/src/main/groovy/ru/sberbank/school/task03/ResponseFormatterImpl.groovy
> +                "на объеме ${SolutionFormatter.getUnprofitAmount()}\n"
странное сочетание конкатенация одднострочных строк а объявление однострочной строки как многострочную %)

2019-05-17 20:07 UTC, kolmogorov-aa requested changes
Сквош

2019-05-20 20:25 UTC, kolmogorov-aa commented
Вообще не нужно на каждое изменение делать коммит.

2019-05-21 14:25 UTC, AlexeyDomnin commented
START-TEST

2019-05-21 17:57 UTC, merged