2
sberbankjavaschool/homework pull request #20
Opened 2019-04-28 11:45 UTC by GWait

2019-04-28 12:19 UTC, kolmogorov-aa commented
START-TEST

2019-04-28 15:53 UTC, kolmogorov-aa commented
START-TEST

2019-04-28 17:49 UTC, kolmogorov-aa commented on solutions/src/test/java/ru/sberbank/school/task02/ConverterTest.java
> +        BigDecimal convert = conv.convert(ClientOperation.BUY, Symbol.USD_RUB, BigDecimal.valueOf(100.00000000000000000000000003));
Надо исправить

2019-04-28 17:49 UTC, kolmogorov-aa commented
START-TEST

2019-04-28 18:05 UTC, kolmogorov-aa requested changes
два цикла подряд - не айс.

2019-04-28 18:05 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +        if (amount.compareTo(BigDecimal.ZERO) <= 0 || quotes.size() <= 0) {
Всё же сначала надо проверить аргументы, а затем уже обращаться к сервису. 
Symbol, кстати, может быть null.

2019-04-28 18:05 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return o1.getVolumeSize().compareTo(o2.getVolumeSize());
А как сделать без сортировки? Можно ли? Есть ли профит от этого?

2019-04-28 18:05 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return getInfQuote(quotes);
Как-то не очень красиво. А можно это за один прогон целый прогон цикла понять?

2019-04-28 18:05 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +    private Quote getMatchedQuote(List<Quote> quotes, BigDecimal amount) {
То что на методы бьёте - хорошо

2019-04-28 18:44 UTC, GWait commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return o1.getVolumeSize().compareTo(o2.getVolumeSize());
> А как сделать без сортировки? Можно ли? Есть ли профит от этого?

Сделать можно, перебрать все и выбрать подходящий, но это ведь сложнее логика получается. Проще сразу отсортировать и всегда знать, что далее идут квоты только больше.

2019-04-28 19:38 UTC, GWait commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return o1.getVolumeSize().compareTo(o2.getVolumeSize());
private Quote getMatchedQuoteTest(List<Quote> quotes, BigDecimal amount) {
        Quote tmp = getInfQuote(quotes);
        for (Quote q : quotes) {
            if (q.getVolumeSize().compareTo(amount) > 0 && q.getVolumeSize().compareTo(tmp.getVolumeSize()) < 0 && !q.isInfinity()) {
                tmp = q;
            }
        }
        return tmp;
    }

Но строка больше 120 символов :D

2019-04-28 19:57 UTC, GWait commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return o1.getVolumeSize().compareTo(o2.getVolumeSize());
private Quote getMatchedQuote2(List<Quote> quotes, BigDecimal amount) {
        List<Quote> matchedQuotes = new ArrayList<>();
        for (Quote q : quotes) {
            if (q.getVolumeSize().compareTo(amount) > 0) {
                matchedQuotes.add(q);
            }
        }
        if (matchedQuotes.size() <= 0) {
            return getInfQuote(quotes);
        }
        Quote res = matchedQuotes.get(0);
        for (Quote q : matchedQuotes) {
            if (res.getVolumeSize().compareTo(q.getVolumeSize()) > 0) {
                res = q;
            }
        }
        return res;
    }

2019-04-28 19:58 UTC, GWait commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return o1.getVolumeSize().compareTo(o2.getVolumeSize());
Думаю, проще отсортировать :)

2019-04-29 06:38 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return o1.getVolumeSize().compareTo(o2.getVolumeSize());
Можно и за один цикл сделать.
Отсортировать проще, но не всегда это позволительно

2019-04-29 06:42 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +        if (amount.compareTo(BigDecimal.ZERO) <= 0 || quotes.size() <= 0) {
Уже лучше, но всё равно, если у нас amount < 0 зачем-то вызывается сервис service.getQuotes, только для того чтобы потом вернуть null

2019-04-29 06:44 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return getInfQuote(quotes);
Я в первый раз не заметил, что их тут три было.
Тем не менее их осталось два.
Такой код не пройдет код-ревью в серьёзный в боевой проект, поэтому тренируемся здесь и сейчас.

2019-04-29 12:58 UTC, GWait commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return getInfQuote(quotes);
> Я в первый раз не заметил, что их тут три было.
> Тем не менее их осталось два.
> Такой код не пройдет код-ревью в серьёзный в боевой проект, поэтому тренируемся здесь и сейчас.

В исправленном коде в этом месте вообще нет циклов

2019-04-29 14:12 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return getInfQuote(quotes);
а в getInfQuote не цикл что ли?

2019-04-29 14:16 UTC, GWait commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return getInfQuote(quotes);
> а в getInfQuote не цикл что ли?

Это место сейчас выгляди так

Quote matchedQuote = getMatchedQuote(quotes, amount);
        if (matchedQuote == null) {
            return null;
        }
        return operation == ClientOperation.SELL ? matchedQuote.getBid() : matchedQuote.getOffer();

2019-04-29 14:23 UTC, GWait commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return getInfQuote(quotes);
Сегодня вечером постараюсь сделать без сортировки в один цикл.

2019-04-29 14:27 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return getInfQuote(quotes);
Ок. Не обязательно делать без сортировки, но важно сделать в один цикл.
Опять же циклы просто переехали не важно где они  в коде, их всё равно два.
![image](https://user-images.githubusercontent.com/36761659/56903001-1fab1f80-6aa4-11e9-9b5e-2a98691b944a.png)

2019-04-29 22:50 UTC, GWait commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +            return o1.getVolumeSize().compareTo(o2.getVolumeSize());
> Можно и за один цикл сделать.
> Отсортировать проще, но не всегда это позволительно

Готово. Логика без сортировки и в один цикл, все разбито на методы.

2019-05-01 14:41 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +        Quote infQuote = null;
Можно и без доп. переменной обойтись.

2019-05-01 14:41 UTC, kolmogorov-aa approved these changes

2019-05-01 14:42 UTC, merged