(9) Zahoda
sberbankjavaschool/homework pull request #270
Opened 2019-05-30 18:24 UTC by RinRowRow

2019-05-30 19:53 UTC, kolmogorov-aa commented
START-TEST

2019-05-30 19:53 UTC, kolmogorov-aa commented
А чего файлов опять так много? как это смотреть вообще? =)

2019-05-30 19:56 UTC, RinRowRow commented
Не знаю, откуда они вылезают(. Сейчас попробую исправить.

2019-05-30 20:07 UTC, RinRowRow commented
Исправил :3. Чуть позже сравню с другими реализациями.

2019-05-30 23:41 UTC, RinRowRow commented
Сравнил с Java Serialization и Externalizable.
За основу взял Route от Москвы до Берлина (не спецом, просто рандомные вбил хд). Провел 10 испытаний на каждом сервисе.
Размеры файлов (в байтах):
Java Serialization: 1683; Externalizable: 1605; Kryo: 520-523 (интересно, почему размер меняется).
__________________________________________________________________________________________________________
Среднее время сериализация (в миллисекундах):
Java Serialization: 5.02; Externalizable: 5.5; Kryo: 0.287.
__________________________________________________________________________________________________________
Среднее время десериализации (в миллисекундах):
Java Serialization: 1.43; Externalizable: 1.26; Kryo: 0.88.

2019-05-31 15:09 UTC, kolmogorov-aa requested changes
Не все условия выполнены.
Не засчитываю

2019-05-31 15:09 UTC, kolmogorov-aa commented on solutions/src/test/java/ru/sberbank/school/task09/RouteServiceTest.java
> +    @DisplayName("Сравнение сгенерированного и считанного из кэша объектов.")
Этот тест у меня не проходит

2019-05-31 15:09 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/KryoSerializer.java
> +        route.setCities(kryo.readObject(input, LinkedList.class));
А сериализатор для City где?

Инстансы неправильно создаете

2019-06-01 07:11 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java~HEAD
> +package ru.sberbank.school.task02;
это мусор здесь зачем?

2019-06-01 13:36 UTC, RinRowRow commented on solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java~HEAD
> +package ru.sberbank.school.task02;
Убрал. Честно говоря, не знаю, откуда он там взялся о.О.

2019-06-01 17:11 UTC, kolmogorov-aa approved these changes

2019-06-01 17:11 UTC, merged