(9) Romanova
sberbankjavaschool/homework pull request #271
Opened 2019-05-30 20:54 UTC by anatennis

2019-05-31 11:28 UTC, kolmogorov-aa commented
START-TEST

2019-05-31 16:39 UTC, kolmogorov-aa requested changes

2019-05-31 16:39 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/CityKryoSerializer.java
> +        return new City(id, name, date, inhabitans, nearcityObjects);
Как минимум, десериализация сделана неправильно.
Теряется идентичность объектов. Это надо обязательно исправить - в этом весь смысл задания.

2019-05-31 16:39 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/CityKryoSerializer.java
> +        return new City(id, name, date, inhabitans, nearcityObjects);
Дальше я пока не смотрел

2019-05-31 16:43 UTC, anatennis commented on solutions/src/main/java/ru/sberbank/school/task09/CityKryoSerializer.java
> +        return new City(id, name, date, inhabitans, nearcityObjects);
Да, я заметила замечание в ридми про сериализатор для каждой сущности уже после того, как попросила вас посмотреть, так что он пока не работает

2019-05-31 17:21 UTC, kolmogorov-aa commented
START-TEST

2019-05-31 17:27 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/CityKryoSerializer.java
> +        City city = new City();
Неа

2019-06-01 07:07 UTC, kolmogorov-aa approved these changes

2019-06-01 07:07 UTC, merged