(9) Targon
sberbankjavaschool/homework pull request #273
Opened 2019-05-30 22:31 UTC by NickTargon

2019-05-31 04:34 UTC, NickTargon commented
Алексей, пока не сравнивал, смогу добавить результаты сравнения только вечером

2019-05-31 15:13 UTC, kolmogorov-aa commented
> Алексей, пока не сравнивал, смогу добавить результаты сравнения только вечером

Тупанул,я ж убрал требования несколько вариаций сделать. Чего там сравнивать? Убрал и условие из задачи.

2019-05-31 15:19 UTC, kolmogorov-aa requested changes
айайай

2019-05-31 15:19 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task08/SerializableManager.java
> +            try (ObjectOutputStream oos = new ObjectOutputStream(os)) {
А зачем ТАК?

2019-05-31 15:19 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +    private void initialized() {
метод кривовато назван

2019-05-31 15:19 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +    public void cacheRout(@NonNull Route<City> route) throws RouteFetchException {
очепятка в названии метода

2019-05-31 15:19 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +                + ((City)cities.get(cities.size() - 1)).getCityName();
зачем ТАКИЕ сложности? уверен, что можно и проще и симпатичнее реализовать

2019-05-31 15:19 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/RouteSerializer.java
> +        return new Route<>(inName, inCities);
Во-первых, кто для City будет сериализатор делать? =)
Во-вторых, инстансы надо иначе в крио создавать. так тоже (что-то как-то) работать будет, но нужно иначе.

2019-05-31 15:28 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task08/SerializableManager.java
> +            try (ObjectOutputStream oos = new ObjectOutputStream(os)) {
чтоб чекстайл не ругался, ну еще можно сделать анонимным FileOutputStream

2019-05-31 15:29 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +    private void initialized() {
поменял

2019-05-31 15:29 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +    public void cacheRout(@NonNull Route<City> route) throws RouteFetchException {
поправил

2019-05-31 15:36 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +                + ((City)cities.get(cities.size() - 1)).getCityName();
поменял

2019-05-31 17:10 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task09/RouteSerializer.java
> +        return new Route<>(inName, inCities);
Для City сериализатор сделал

2019-05-31 17:11 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task09/RouteSerializer.java
> +        return new Route<>(inName, inCities);
изменил создание инстансов

2019-05-31 17:21 UTC, kolmogorov-aa commented
START-TEST

2019-05-31 17:22 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task08/SerializableManager.java
> +            try (ObjectOutputStream oos = new ObjectOutputStream(os)) {
или можно отступов добавить?

2019-05-31 17:26 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/CitySerializer.java
> +        City result = new City();
ну почти

2019-06-01 07:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +        try (Input input = new Input(new FileInputStream(file))) {
ну камон, FileInputStream то кто закрывать будет?

2019-06-01 08:59 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task09/CitySerializer.java
> +        City result = new City();
исправил

2019-06-01 08:59 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +        try (Input input = new Input(new FileInputStream(file))) {
переделал

2019-06-01 09:09 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task08/KryoManager.java
> +            try (Output output = new Output(os)) {
Не уверен, что такая запись менее эффективна, но точно не более.

2019-06-01 09:10 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +        TimeSerializers.addDefaultSerializers(kryo);
яможете объяснить чем отличаются kryo.register(LocalDate.class); и TimeSerializers.addDefaultSerializers(kryo);?

2019-06-01 09:10 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +                              Output out = new Output(os)) {
то так то сяк %)

2019-06-01 09:10 UTC, kolmogorov-aa approved these changes

2019-06-01 09:10 UTC, kolmogorov-aa commented on solutions/src/test/java/ru/sberbank/school/task09/KryoRouteServiceTest.java
> +        Assertions.assertNotSame(original, fromCache);
слабоваты тесты то

2019-06-01 09:11 UTC, merged

2019-06-01 09:24 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task09/KryoRouteService.java
> +        TimeSerializers.addDefaultSerializers(kryo);
Как я понимаю в TimeSerializers.addDefaultSerializers(kryo);, добавляются сериализаторы для классов даты и времени, в том числе и тот, который будет взят и здесь kryo.register(LocalDate.class);