(9) Горских
sberbankjavaschool/homework pull request #274
Opened 2019-05-31 05:12 UTC by OLGGOR

2019-05-31 15:26 UTC, kolmogorov-aa requested changes

2019-05-31 15:26 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task08/JaxbManager.java
> +            unmarshaller = context.createUnmarshaller();
вроде обсуждали это и вот опять =)

2019-05-31 15:26 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +public class FixedThreadPool implements ThreadPool {
Лучше в отдельной ветке вести разработку, а эти изменения убрать
Иначе на следующем ПР тут будет каша из изменений, а не новый нормальный файл

2019-05-31 15:26 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task09/util/KryoSerializer.java
> +        List<City> cities = (LinkedList<City>) kryo.readObject(input, LinkedList.class);
Во-первых, кто для City будет сериализатор делать? =)
Во-вторых, инстансы надо иначе в крио создавать. так тоже (что-то как-то) работать будет, но нужно иначе.

2019-05-31 15:49 UTC, OLGGOR commented on solutions/src/main/java/ru/sberbank/school/task08/JaxbManager.java
> +            unmarshaller = context.createUnmarshaller();
Да и я перенесла это в метод инициализации... А как правильно? Сразу написать так:  private JAXBContext context = JAXBContext.newInstance(JaxbMapState.class); ?

2019-06-01 17:12 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task08/JaxbManager.java
> +            unmarshaller = context.createUnmarshaller();
Маршаллеры не должны быть в поле класса не потокобезопасны.

2019-06-01 17:13 UTC, kolmogorov-aa commented on solutions/src/test/java/ru/sberbank/school/task08/JacksonManagerTest.java
> +    private static String directoryPath = "C:\\Users\\1357028\\Desktop\\Save";
Интересно как этот тест на сервере проходит, где диска C в принципе нет?

2019-06-01 17:22 UTC, kolmogorov-aa approved these changes

2019-06-01 17:22 UTC, merged

2019-06-01 17:27 UTC, OLGGOR commented on solutions/src/test/java/ru/sberbank/school/task08/JacksonManagerTest.java
> +    private static String directoryPath = "C:\\Users\\1357028\\Desktop\\Save";
¯\_(ツ)_/¯ чудо какое-то