(10) Romanova
sberbankjavaschool/homework pull request #288
Opened 2019-06-04 12:56 UTC by anatennis

2019-06-04 19:56 UTC, kolmogorov-aa requested changes
есть серьёзные ошибки

2019-06-04 19:56 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +            t = null;
А это зачем?

2019-06-04 19:56 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +                            e.printStackTrace();
Ничего не забыли?

2019-06-04 19:56 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                threads.get(threads.size()-1).start();
не игнорируйте

2019-06-04 19:56 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                threads.add(new ThreadWorker(threads.size()));
Хитрый, но неправильный способ задания уникальных имен.
Допустим у вас 5 тредов в пуле: 
т1, т2, т3, т4,  т5, все хорошо, но тут T1 умирает - runtime exception или мало ли что. Создаем по этому алгоритму новый т2, т3, т4, т5, *т5*

2019-06-04 19:56 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                threads.remove(0);
И всё? ничего не забыли?

2019-06-04 19:56 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +            }
Не понял что это условие делает *тут*?

2019-06-04 19:56 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                task.run();
Неплохо было бы хоть какую-то политику обработки исключений обозначить

2019-06-04 19:56 UTC, kolmogorov-aa commented on solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolTest.java
> +        }
Это не тест, он ничего не проверяет

2019-06-04 19:56 UTC, kolmogorov-aa commented on solutions/src/test/java/ru/sberbank/school/task10/ScalableThreadPoolTest.java
> +        }
и это не тест

2019-06-04 20:52 UTC, anatennis commented on solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolTest.java
> +        }
Да, пока тестов тут нет, это просто для запуска добавлено

2019-06-04 20:52 UTC, anatennis commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                task.run();
Принято

2019-06-04 20:54 UTC, anatennis commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +            }
Это решение еще в процессе разработки, как я говорила, пока все сырое)

2019-06-04 20:54 UTC, anatennis commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                threads.add(new ThreadWorker(threads.size()));
Принято

2019-06-04 21:01 UTC, anatennis commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +                            e.printStackTrace();
Есть подозрения, буду смотреть

2019-06-04 21:06 UTC, anatennis commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +            t = null;
И правда

2019-06-05 07:36 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +    public void execute(Runnable runnable) {
А ещё вот такой вопрос. Что будет если в уже остановленный тредпул попытаются отправить задачу?

2019-06-05 10:09 UTC, anatennis commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +    public void execute(Runnable runnable) {
Непредсказуемо, может и зависнуть. Исправлю.

2019-06-07 11:21 UTC, kolmogorov-aa approved these changes

2019-06-07 11:21 UTC, merged