(10) Лобанова
sberbankjavaschool/homework pull request #289
Opened 2019-06-04 15:24 UTC by alobanova

2019-06-05 07:24 UTC, kolmogorov-aa requested changes
И ещё не понял что тесты то проверяют.

2019-06-05 07:24 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +public class FixedThreadPool extends ScalableThreadPool implements ThreadPool {
Серьёзно? =)

2019-06-05 07:24 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +    private void correctSizeThreadPool() {
Если уж поддерживать наследование, то в дочернем классе этот метод не нужен.

2019-06-05 07:24 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +            if (tasks.size() > minSizePool) {
А если у нас есть задачи, но их количество не превышает минимального размера пула? Они будут продолжать ждать?

2019-06-05 07:24 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                if (thread.getState() == Thread.State.NEW) {
Гарантирует ли такая проверка, что метод start() не был вызван? Может быть и не в конкретном случае, а вообще?

2019-06-05 07:24 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +        synchronized (tasks) {
Вопрос по методу. А вот что если в это время будут параллельно сабмититься задачи? А если после?

2019-06-05 07:24 UTC, kolmogorov-aa commented on solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolTest.java
> +            Thread.sleep(100);
Так себе заслончик. Как решить это красиво мы узнаем в субботу, но и сейчас можно было бы более надёжное решение применить.

2019-06-05 07:24 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                if (task != null) {
А в каких случаях такое возможно?

2019-06-05 07:39 UTC, alobanova commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +public class FixedThreadPool extends ScalableThreadPool implements ThreadPool {
Я подумала что там можно было :)
Убрать?

2019-06-05 07:43 UTC, alobanova commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +    private void correctSizeThreadPool() {
Да этот метод вызывается в дочернем классе, но сразу же из него выходит, так как там цикл от минимального до максимального.

2019-06-05 15:00 UTC, alobanova commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                if (task != null) {
Это возможно при прерывание. Тред выйдет из ожидания, а задачи в очереди не будет.

2019-06-05 15:53 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +    private void correctSizeThreadPool() {
Справедливо

2019-06-05 15:54 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                if (task != null) {
Тогда там можно прервать выполнение функции.

2019-06-06 08:14 UTC, alobanova commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                if (task != null) {
Готово

2019-06-06 08:14 UTC, alobanova commented on solutions/src/test/java/ru/sberbank/school/task10/FixedThreadPoolTest.java
> +            Thread.sleep(100);
Полностью согласна. Самой это решение не нравится.

2019-06-06 08:14 UTC, alobanova commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +        synchronized (tasks) {
Попробовала так сделать. Выскочила ошибка NullPointerException. (Логично потоков же нет)
Добавила проверку в метод execute, чтобы после остановки пула им нельзя было пользоваться.

2019-06-06 08:14 UTC, alobanova commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                if (thread.getState() == Thread.State.NEW) {
Похоже не гарантирует, так как к моменту, когда мы прочтем состояние треда, оно может измениться.
Но в моем конкретном случае, такого не должно произойти. Запускаются треды при синхронизации.

2019-06-06 08:15 UTC, alobanova commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +            if (tasks.size() > minSizePool) {
Исправила. Теперь если больше одной задачи в очереди, подключатся новые потоки.

2019-06-07 11:26 UTC, kolmogorov-aa approved these changes

2019-06-07 11:26 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +            throw new NullPointerException("Thread pool not running");
Ну нет, не NPE. IllegalState

2019-06-07 11:26 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                if (thread.getState() == Thread.State.NEW) {
Ну да

2019-06-07 11:26 UTC, merged