(2) Naumovec
sberbankjavaschool/homework pull request #29
Opened 2019-05-02 17:31 UTC by tatanka27

2019-05-02 20:27 UTC, kolmogorov-aa requested changes

2019-05-02 20:27 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +        if (operation == null || symbol == null || amount == null) {
не очень хорошо. в итоге не понятно какой из параметров был null

2019-05-02 20:27 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new ConverterConfigurationException("Parameters should be null!");
а бросать лучше NPE

2019-05-02 20:27 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new ConverterConfigurationException("Amount less than or equal to 0!");
а тут illegalArgument

2019-05-02 20:27 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +        // получаем отсортированный массив котировок
Опять таки лишний коммент.

2019-05-02 20:27 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +        quotes.sort(comparator);
Ну, что, обсудим?..
Во-первых, почему компаратор локальная переменная, а не поле класса? =) При каждом вызове метода будет создаваться новый объект, а это не то чего мы хотим, верно?.
Во-вторых, это достаточно простое с т.з. реализации решение. А можно как-то без сортировки, ведь скорее всего можно нарваться на квадратичную сложность (ну или n*log(n) в лучшем случае). Спойлер: можно. Вопрос - как?

2019-05-02 20:27 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new ConverterConfigurationException("No quotes!");
Хорошо, но там должно быть исключение по-лучше.

2019-05-02 20:27 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Solution.java
> +                    Symbol.USD_RUB, new BigDecimal(100));
new BigDecimal(100) - так, по-моему, не стоит BigDecimal создавать. Посмотрите на описание конструкторов.
используйте valueof()

2019-05-02 20:27 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +                price = operation.compareTo(ClientOperation.BUY) == 0 ? q.getOffer() : q.getBid();
operation.compareTo(ClientOperation.BUY) == 0
Хорошая попытка, но нет. Enum сравнивается через == и не надо мудрить ;)

2019-05-03 05:27 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +        quotes.sort(comparator);
Пойду думать, как сделать без сортировки тогда.

2019-05-03 05:28 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new ConverterConfigurationException("No quotes!");
Ок, почищу исключения.

2019-05-03 05:47 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +                price = operation.compareTo(ClientOperation.BUY) == 0 ? q.getOffer() : q.getBid();
Перемудрила :)

2019-05-03 06:24 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new ConverterConfigurationException("No quotes!");
А что значит получше?

2019-05-03 13:34 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new NullPointerException("Parameter operation is null!");
ОК. Функционально пойдет. с т.з. чистоты кода не очень. Пока оставим.

2019-05-03 14:59 UTC, kolmogorov-aa approved these changes

2019-05-03 14:59 UTC, merged

2019-05-03 16:08 UTC, tatanka27 commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new NullPointerException("Parameter operation is null!");
Самой не нравится, другой вариант пока не придумала.