(10) Zahoda
sberbankjavaschool/homework pull request #292
Opened 2019-06-05 16:07 UTC by RinRowRow

2019-06-05 18:50 UTC, RinRowRow commented
Нашел кучу косяков. Сейчас отредактирую :3

2019-06-07 11:32 UTC, kolmogorov-aa requested changes
Не могу замержить в таком состоянии

2019-06-07 11:32 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +    public void start() {
Два раза стартануть тредпул. нехорошо будет

2019-06-07 11:32 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +            taskQueue.add(runnable);
ну неее... Оно вообще работает?

2019-06-07 11:32 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +            while (!Thread.interrupted()) {
этот цикл непрерывно работает в каждом треде, так получается?
Busy waiting не хорошо

2019-06-07 11:32 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                        threads.remove(this);
Похоже, что мы имеем дело с самоубийством =)

2019-06-07 13:13 UTC, RinRowRow commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +    public void start() {
Так у меня же с threads.size() цикл начинается.

2019-06-07 13:16 UTC, RinRowRow commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +            taskQueue.add(runnable);
Ааааа. Я правильно понял, что execute можно только после старта вызывать? Я просто думал, что так можно как бы в очередь складывать. Ну тогда понял проблему. Сейчас решу).

2019-06-07 13:18 UTC, RinRowRow commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +    public void start() {
Впрочем. Я так понял, что в целом нельзя позволять 2 раза запускать. Так?

2019-06-07 13:31 UTC, RinRowRow commented on solutions/src/main/java/ru/sberbank/school/task10/FixedThreadPool.java
> +    public void start() {
Ну. Без остановки.

2019-06-08 08:50 UTC, RinRowRow commented
Я еще отредактирую. (Придумал, как сделать код лучше).

2019-06-11 18:06 UTC, kolmogorov-aa approved these changes

2019-06-11 18:06 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +        synchronized (mainLock) {
зачем нужен main lock?

2019-06-11 18:06 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                        synchronized (threads) {
Беда у вас с блокировками их, как мне кажется, очень много. Много блокировок, много мониторов.

по крайней мере мне так показалось, сложно анализировать такой код

2019-06-11 18:06 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                        idsManager.addFreeId(freeThread.getThreadId());
это на грани фантастики... 
очень костыльно выглядит. 

это не страшно на текущем этапе обучения, но не стоит такие техники практиковать.

2019-06-11 18:06 UTC, merged

2019-06-11 18:21 UTC, RinRowRow commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +        synchronized (mainLock) {
Точно. Там достаточно было добавить synchronized в методы. Не подумал)

2019-06-11 18:24 UTC, RinRowRow commented on solutions/src/main/java/ru/sberbank/school/task10/ScalableThreadPool.java
> +                        synchronized (threads) {
У меня была идея с демон потоком, который раз в опр время чистит неиспользуемые потоки, но тогда бы пришлось в нем или проходить по всем тредам и проверять на isAlive. Так что тут тоже была бы неприятная блокировка. Или создать отдельный список "освобожденных" потоков, но тогда непонятно, как их в этот список добавлять(