(2) Zahoda
sberbankjavaschool/homework pull request #39
Opened 2019-05-03 23:39 UTC by RinRowRow

2019-05-04 00:16 UTC, RinRowRow commented
Откатил на старый коммит и ПР свернулся. Заранее извиняюсь за такой косяк ТТ.

2019-05-04 21:24 UTC, kolmogorov-aa requested changes
Вроде норм. Стримы это круто, конечно, но все же не надо пускаться в анархию.
Какая сложность вашего алгоритма получилась в итоге?
Отформатируйте код  и можно мержить.

2019-05-04 21:24 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +        if (operation == null || symbol == null || amount == null) {
Не оч. Оставим на потом

2019-05-04 21:24 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +                }).orElse(quotes.get(0));
Форматирование стрима хромает ппц.
https://bormoshka.ru/как-сделать-код-на-стримах-чище/

2019-05-05 01:30 UTC, RinRowRow commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +        if (operation == null || symbol == null || amount == null) {
Лучше использовать @NotNull?

2019-05-05 06:03 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +        if (operation == null || symbol == null || amount == null) {
Не обязательно. Как вы поймёте какой из аргументов null?

2019-05-05 09:44 UTC, RinRowRow commented on solutions/src/main/java/ru/sberbank/school/task02/Converter.java
> +        if (operation == null || symbol == null || amount == null) {
А вот об это я действительно не подумал!

2019-05-05 13:09 UTC, RinRowRow commented
START-TEST

2019-05-05 14:10 UTC, RinRowRow commented
Ого. Без стрима значительно быстрее!

2019-05-05 15:09 UTC, kolmogorov-aa approved these changes

2019-05-05 15:10 UTC, merged