(2) Malygin
sberbankjavaschool/homework pull request #47
Opened 2019-05-04 17:36 UTC by Vladimir-prog

2019-05-04 21:29 UTC, kolmogorov-aa requested changes
Зачем то дистр гредла поменяли.
И лишний цикл.

2019-05-04 21:29 UTC, kolmogorov-aa commented on gradle/wrapper/gradle-wrapper.properties
>  zipStorePath=wrapper/dists
Эм? А чего такое?

2019-05-04 21:29 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
> +        for (Quote currentQuote : quoteList) {
Зачем этот цикл нужен?
Вопрос риторический. Он не нужен. Эта задача решается в одну итерацию.

2019-05-05 04:58 UTC, Vladimir-prog commented on solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
> +        for (Quote currentQuote : quoteList) {
Убрал второй цикл

2019-05-05 06:08 UTC, kolmogorov-aa requested changes
Лишний файл убрать и можно мержить.

2019-05-05 06:08 UTC, kolmogorov-aa commented on gradle/wrapper/gradle-wrapper.properties
> +zipStorePath=wrapper/dists
Мелочь, а может вызвать проблемы при мерже. Лишних файлов быть не должно, следите за этим

2019-05-05 06:17 UTC, Vladimir-prog commented on gradle/wrapper/gradle-wrapper.properties
> +zipStorePath=wrapper/dists
готово

2019-05-05 06:18 UTC, kolmogorov-aa approved these changes

2019-05-05 06:18 UTC, merged