(3) Таргон
sberbankjavaschool/homework pull request #54
Opened 2019-05-05 15:08 UTC by NickTargon

2019-05-05 16:24 UTC, kolmogorov-aa commented
START-TEST

2019-05-05 16:27 UTC, kolmogorov-aa commented
START-TEST

2019-05-05 16:31 UTC, kolmogorov-aa commented
START-TEST

2019-05-05 16:58 UTC, NickTargon commented
START-TEST

2019-05-05 17:14 UTC, NickTargon commented
START-TEST

2019-05-05 17:17 UTC, kolmogorov-aa commented
START-TEST

2019-05-05 17:22 UTC, kolmogorov-aa commented
START-TEST

2019-05-05 17:30 UTC, kolmogorov-aa commented
START-TEST

2019-05-05 17:41 UTC, kolmogorov-aa commented
START-TEST

2019-05-05 18:00 UTC, kolmogorov-aa commented
START-TEST

2019-05-05 18:07 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryForCurrCalc.java
> +        return null;
Кхм... А это кто определять будет?

2019-05-05 18:08 UTC, kolmogorov-aa requested changes

2019-05-05 18:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ServiceFactoryImpl.java
> +public class ServiceFactoryImpl implements ServiceFactory {
Нет, фабрика должна быть одна.

2019-05-05 18:18 UTC, NickTargon commented
START-TEST

2019-05-05 18:19 UTC, NickTargon commented
START-TEST

2019-05-05 18:47 UTC, NickTargon commented
START-TEST

2019-05-08 20:15 UTC, NickTargon commented
START-TEST

2019-05-09 18:49 UTC, closed without merging