Upload
sberbankjavaschool/homework pull request #7
Opened 2019-04-25 17:58 UTC by bahusdivus

2019-04-25 19:29 UTC, kolmogorov-aa commented
Не надо гадать =) Ща разберемся

2019-04-25 19:31 UTC, kolmogorov-aa commented
Надо сделать pull из source
Всегда смотрите за этой веткой. 
Я постараюсь сделать автоматический pull-push, но не обещаю, что в скором времени

2019-04-25 21:31 UTC, bahusdivus commented
TEST ME

2019-04-28 07:47 UTC, kolmogorov-aa commented
id - без id

2019-04-28 08:45 UTC, kolmogorov-aa commented
START-TEST

2019-04-28 15:53 UTC, kolmogorov-aa commented
START-TEST

2019-04-28 16:26 UTC, kolmogorov-aa commented
START-TEST

2019-04-28 16:31 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            if (quote.isInfinity() || amount.compareTo(quote.getVolumeSize()) <= 0) {
верхний объем исключительно

2019-04-28 17:01 UTC, kolmogorov-aa requested changes
лишние файлы надо убрать, остальные замечания для дискуссии.

2019-04-28 17:01 UTC, kolmogorov-aa commented on .idea/vcs.xml
> +</project>
Этих файлов быть не должно в ПР

2019-04-28 17:01 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
а если null? =)

2019-04-28 17:01 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +        if (quotes.size() == 0) {
isEmpty() тогда уж

2019-04-28 17:01 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +        quotes.sort((right, left) -> {
В принципе пойдет, а если без сортировки, можно как-то красиво сделать?

2019-04-28 17:01 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +                break;
else - break как-то излишне выглядит, как бы это получше записать?

2019-04-28 17:01 UTC, kolmogorov-aa commented on solutions/src/test/java/ru/sberbank/school/task02/CalculatorTest.java
> +                BigDecimal.valueOf(1005.0410071948494));
Хех ;)

2019-04-28 17:37 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExternalQuotesProvider.java
> +        quotes.add(new Quote(symbol, Volume.from(-1), new BigDecimal(1000), new BigDecimal(10000)));
Volume.INFINITY!

2019-04-28 18:56 UTC, bahusdivus commented on .idea/vcs.xml
> +</project>
Fixed

2019-04-28 18:56 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
Fixed

2019-04-28 18:56 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +        if (quotes.size() == 0) {
Fixed

2019-04-28 18:57 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +        quotes.sort((right, left) -> {
Сделал без сортировки и другим циклом

2019-04-28 18:57 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +                break;
Сделал без сортировки и другим циклом

2019-04-28 18:57 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/ExternalQuotesProvider.java
> +        quotes.add(new Quote(symbol, Volume.from(-1), new BigDecimal(1000), new BigDecimal(10000)));
Fixed

2019-04-29 06:35 UTC, kolmogorov-aa approved these changes
Минорные проблемы остались, исправите потом

2019-04-29 06:35 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            if (quote.isInfinity() && (current == null)) {
(current == null)
скобки лишние и мешают восприятию

2019-04-29 06:35 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +                if ((current == null) || current.isInfinity()
и тут 4 лишних скобки

2019-04-29 06:35 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            return null;
А это возможно?

2019-04-29 06:35 UTC, merged

2019-04-29 07:04 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            return null;
IDEA ругается иначе. Есть сценарий, вызывающий NullPointerException: в списке котировок нет диапазона INFINITY и amount больше максимального.