(3) Южаков
sberbankjavaschool/homework pull request #81
Opened 2019-05-08 14:50 UTC by bahusdivus

2019-05-08 16:15 UTC, bahusdivus commented
Если это действительно успешное решение, не мержте пока, я попробую доделать дельту

2019-05-08 17:01 UTC, bahusdivus commented
START-TEST

2019-05-08 21:21 UTC, kolmogorov-aa requested changes
Поправить исключения и ОК

2019-05-08 21:21 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new NullPointerException();
Плохо. С Вас ответ почему.

2019-05-08 21:21 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
>              return null;
тут так-то тоже можно бросать исключение.
но делать сейчас этого уже не надо

2019-05-08 21:21 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +            throw new IllegalArgumentException();
amount == null
new IllegalArgumentException();
???

2019-05-08 21:21 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +                    : amount.divide(quote.getOffer(), 10, RoundingMode.HALF_UP);
выглядит громоздко, ну ладно, чего уж

2019-05-08 21:21 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +                : BigDecimal.ONE.divide(current.getOffer(), 10, RoundingMode.HALF_UP);
подобный код, был выше...

2019-05-08 21:21 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +        return Optional.empty();
ОК, вижу.

2019-05-09 10:44 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new NullPointerException();
???

2019-05-09 10:45 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +            throw new NullPointerException();
Что тут не так?

2019-05-09 10:49 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +            throw new NullPointerException();
Не дает понимания, какой именно аргумент == null? Есть мысль вынести валидацию в отдельный метод и там выполнить проверку с несколькими if. Это приемлемая практика?

2019-05-09 10:50 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +            throw new IllegalArgumentException();
Поправил в следующем коммите.

2019-05-09 10:51 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/Calculator.java
> +            throw new NullPointerException();
Ответил ниже

2019-05-09 10:51 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +                    : amount.divide(quote.getOffer(), 10, RoundingMode.HALF_UP);
Лучше эту конструкцию реализовать без тернарника?

2019-05-09 11:47 UTC, kolmogorov-aa commented
START-TEST

2019-05-09 12:42 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +        return Optional.empty();
Реализовал

2019-05-09 20:28 UTC, bahusdivus commented
START-TEST

2019-05-09 20:31 UTC, bahusdivus commented
Изменил тайтл, чтобы сдать завтрашнее задание и потом мучиться с "сумеречной зоной"

2019-05-10 06:14 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +            throw new NullPointerException();
Objects.requireNotNull

2019-05-10 06:16 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
> +            this.beneficiary = Beneficiary.BANK;
Вот если бы у enum был подходящий для этих целей...

2019-05-10 06:18 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
> +        Optional<BigDecimal> price = calculator.convertReversed(operation, symbol, amount, beneficiary);
Неплохо было бы отлавливать ошибки сервиса и подбрасывать соот. Уровня

2019-05-10 06:20 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +                    amount.subtract(BigDecimal.valueOf(delta)), beneficiary);
Нее, так делать нельзя.

2019-05-10 06:21 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
> +            throw new ConverterConfigurationException("You should provide exactly 3 params: symbol, direction, amount");
А не лучше ли сначала проверить аргументы, а потом уже создавать сервисы?

2019-05-10 06:23 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
> +        FxRequest request = new FxRequest(args[0], args[1], args[2]);
Так очень некрасиво представьте себе программу в которую просто передаются аргументы в сирогоумтановленном порядке. Без ключей и подписей.

2019-05-10 06:23 UTC, merged

2019-05-10 15:30 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
> +            this.beneficiary = Beneficiary.BANK;
Про .valueOf не подумал =( Исправил

2019-05-10 15:37 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
> +        Optional<BigDecimal> price = calculator.convertReversed(operation, symbol, amount, beneficiary);
Не понимаю, что имеется ввиду =(

2019-05-10 15:41 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +                    amount.subtract(BigDecimal.valueOf(delta)), beneficiary);
Почему? На занятии говорилось, что дельта в абсолютной величине в рублях. Или тут какая-то другая ошибка?

2019-05-10 15:42 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
> +            throw new ConverterConfigurationException("You should provide exactly 3 params: symbol, direction, amount");
Поправил

2019-05-10 15:46 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
> +        FxRequest request = new FxRequest(args[0], args[1], args[2]);
Красивее будет вызов примерно такого вида?
java FxClientControllerImpl -amount 1000 -beneficiary BANK -direction SELL

2019-05-10 18:38 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
> +        FxRequest request = new FxRequest(args[0], args[1], args[2]);
да

2019-05-10 18:40 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +                    amount.subtract(BigDecimal.valueOf(delta)), beneficiary);
другая. Вы два раза дергаете сервис convertReversed.
ну и логически чисто это неправильно, результаты будут (могут быть) неверными.
Вы можете перескочить объем и т.п.

на этот метод тестов нет.

2019-05-11 09:24 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/FxClientControllerImpl.java
> +        FxRequest request = new FxRequest(args[0], args[1], args[2]);
Исправил

2019-05-11 09:24 UTC, bahusdivus commented on solutions/src/main/java/ru/sberbank/school/task02/ReverseCalculator.java
> +            throw new NullPointerException();
Исправил