(3) Romanova
sberbankjavaschool/homework pull request #86
Opened 2019-05-08 20:08 UTC by anatennis

2019-05-08 20:38 UTC, anatennis commented
Попробую еще второй вариант сделать, если этот правильный..)

2019-05-08 21:22 UTC, kolmogorov-aa commented
Как исправить конфликты:
1. вычекать ветку source из общего репо в новую локальную ветку,
2. сделать pull из своей ветки общего репо.
3. Сделать пулл со своей текущей ветки выбрать squash commits.
4. сделать force-push в ветку в своём форке

2019-05-08 21:26 UTC, kolmogorov-aa requested changes
Конфликты

2019-05-08 21:26 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
> +        }
???
Что за сложности на ровном месте? =)

2019-05-08 21:26 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
> +        }
и тут. знаю как можно запросто укоротить метод на 7 строчек

2019-05-08 21:26 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
> +        return Optional.ofNullable(price);
А вообще хитро

2019-05-09 11:48 UTC, kolmogorov-aa commented
START-TEST

2019-05-09 17:46 UTC, kolmogorov-aa commented
а потому что оно и не работает. Пересоздайте ПР, из-за конфликтов сборка невозможна

2019-05-09 17:46 UTC, closed without merging

2019-05-10 08:21 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
> +                convert(ClientOperation.BUY, symbol, rightAmount);
когда я предлагал сократить. то имел ввиду несколько другое
revertedOperation = operation == BUY ? SELL : BUY;
и вместо 4х convert(ClientOperation.SELL, symbol, amount) : два convert(revertedOperation , symbol, amount)
это может показаться мелочью, но это отличает просто рабочий код от хорошего кода.

2019-05-10 08:21 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
> +        return Optional.ofNullable(price);
Настолько хитро что я не могу понять как оно работает.

2019-05-10 08:21 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/FxConversionServiceImpl.java
> +                convert(ClientOperation.BUY, symbol, amount);
Вот это очень странная операция. Мы из метода конверт для инструмента USD/RUB получим значение цены 1000 usd, хотя в метод передается 1000 RUB. А потом конвертируетюм это в объем в рублях, но как это вообще работает?

2019-05-10 08:21 UTC, kolmogorov-aa commented
дурацкая система ревью...
забыл отправить в прошлый раз