(4) Таргон
sberbankjavaschool/homework pull request #95
Opened 2019-05-09 18:50 UTC by NickTargon

2019-05-09 20:08 UTC, kolmogorov-aa requested changes
в комментах

2019-05-09 20:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +        if (beneficiary.isEmpty()) {
а если null?

2019-05-09 20:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +            throw new ConverterConfigurationException("Whe haven't got Symbol");
ConverterConfigurationException не то исключение, которое нужно использовать

2019-05-09 20:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +            throw new IllegalArgumentException("'SBRF_BENEFICIARY' must be BANK or CLIENT, current: " + beneficiary);
ConverterConfigurationException - тут тоже нужен. Это не аргумент, а переменная окружения, иними славами - ??? конфигурация. 

ну почти...

2019-05-09 20:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +        BigDecimal amount;
не понял зачем объявлять так

2019-05-09 20:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +        BigDecimal amount;
Лучше было бы парсинг каждой переменной разнести по методам

2019-05-09 20:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCurrencyCalc.java
> +                    + "Symbol: " + symbol + "\n" + "Amount: " + amount + "\n" + "Beneficiary: " + beneficiary);
пока пойдет

2019-05-09 20:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCurrencyCalc.java
> +            throw new IllegalArgumentException("Amount can't be zero or less, current " + amount);
Это то тут откуда?
Это же приватный метод!

2019-05-09 20:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCurrencyCalc.java
> +    public Optional<BigDecimal> convertReversed(ClientOperation operation, Symbol symbol, BigDecimal amount,
Вы же понимаете, что как третье задание я это не зачту, т.к. в заголовке оно не указано (соот. тесты не прогонялись).

2019-05-09 20:08 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCurrencyCalc.java
> +        return Optional.empty();
UnsupportedOperation Да, ведь?

2019-05-09 20:12 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCurrencyCalc.java
> +    public Optional<BigDecimal> convertReversed(ClientOperation operation, Symbol symbol, BigDecimal amount,
Вы имеете в виду задание с id3, я тут только id4 пытаюсь закрыть

2019-05-10 15:36 UTC, kolmogorov-aa requested changes
Но могу принять как 3/4 от максимума

2019-05-10 15:36 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ExtendedCurrencyCalc.java
> +    public Optional<BigDecimal> convertReversed(ClientOperation operation, Symbol symbol, BigDecimal amount,
Да. И я про то же. 
Мне же не очевидно - вы неправильно тайтл заполнили или решили пропустить.

2019-05-10 15:36 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalculator.java
> +            throw  new FxConversionException("There are not quotes for this symbol");
странно, что чекстайл не ругается. тут два пробела между throw и new

2019-05-10 15:36 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +            return string.indexOf('.') != -1 ? string.substring(0, string.indexOf('.') + 3) : string;
Эээм, нет. давайте учиться правильно форматировать числа
https://www.baeldung.com/java-decimalformat

2019-05-10 15:36 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +            throw new NullPointerException("ExtendedFxConversionService can't be null");
Ну так, подсказочка. 
https://tproger.ru/translations/10-ways-to-handle-null-in-java/

2019-05-10 15:36 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +                throw new IllegalArgumentException("Amount hap wrong format, use xxxx.xx");
Amount hap wrong format

2019-05-10 15:36 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +                throw new IllegalArgumentException("Amount hap wrong format, use xxxx.xx");
А если я не хочу передавать дробную часть? Зачем заставлять?

2019-05-10 15:36 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ClientExample.java
> +            FxRequest request = new FxRequest(args[0], args[1], args[2]);
Ну так же некрасиво передавать параметры в строго заданном порядке без указания что из этого что.
Это необязательно к изменению, но так лучше не делать

2019-05-10 17:38 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalculator.java
> +            throw  new FxConversionException("There are not quotes for this symbol");
вот и у меня не ругался, поправил

2019-05-10 17:39 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +            return string.indexOf('.') != -1 ? string.substring(0, string.indexOf('.') + 3) : string;
Изменил метод + добавил нормальную дату

2019-05-10 17:39 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +            throw new NullPointerException("ExtendedFxConversionService can't be null");
Заменил на Objects.requireNonNull

2019-05-10 17:39 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +                throw new IllegalArgumentException("Amount hap wrong format, use xxxx.xx");
Внес исправления

2019-05-10 17:40 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task02/ClientExample.java
> +            FxRequest request = new FxRequest(args[0], args[1], args[2]);
Тоже поправил

2019-05-10 18:33 UTC, kolmogorov-aa approved these changes
ну как-то типа 5 с минусом.

2019-05-10 18:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +        }
Во всех местах нужно было указывать? =)
 Objects.requireNonNull

2019-05-10 18:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +        }
ну что делать и тут подскажу

2019-05-10 18:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +            return ClientOperation.SELL;
подсказка - у енама есть метод для этих целей

2019-05-10 18:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +                return  (BigDecimal) decimalFormat.parse(requests.getAmount());
Пробел заедает? =)

2019-05-10 18:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/ClientExample.java
> +            FxResponse response = client.fetchResult(request);
Ваш метод fetchResult бросает кучу исключений. внутри него сервис тоже бросает кучу исключений.
Пользователю стектрейс будем показывать?

2019-05-10 18:33 UTC, kolmogorov-aa commented on solutions/src/main/java/ru/sberbank/school/task02/CurrencyCalculator.java
> +            throw new NullPointerException("Amount can't be null");
а quote1 может быть null? очень странно.
Метод ещё и протектед.
Был бы приватным - проверять не нужно было бы. 
а так странное что-то

2019-05-10 18:34 UTC, merged

2019-05-10 18:34 UTC, kolmogorov-aa commented
потом исправите замечания.

2019-05-10 18:36 UTC, NickTargon commented
ок, спасибо!

2019-05-10 18:40 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +                return  (BigDecimal) decimalFormat.parse(requests.getAmount());
Ноуту 8 лет, пришлось менять клаву, но оригинальная стоила почти 8к, а китайская всего 2к)) так что это расплата за жадность((

2019-05-10 20:16 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +        }
тут еще и lombok может помочь

2019-05-10 20:58 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task02/Client.java
> +            return ClientOperation.SELL;
поменял

2019-05-10 20:59 UTC, NickTargon commented on solutions/src/main/java/ru/sberbank/school/task02/ClientExample.java
> +            FxResponse response = client.fetchResult(request);
Сделал вывод сообщения с текстом ошибки